export const symptoms = [
  {
    id: 'acquisition',
    label: 'Za mało klientów',
    short: 'Za mało klientów',
    description: 'Robisz marketing, ale liczba zapytań lub sprzedaży nadal jest za mała. Chcesz wiedzieć, co faktycznie warto poprawić.',
    focus: 0.24,
  },
  {
    id: 'conversion',
    label: 'Dużo ruchu, mało zapytań',
    short: 'Mało zapytań',
    description: 'Ludzie wchodzą na stronę, ale niewielu robi kolejny krok. Sprawdzimy, co zatrzymuje ich przed kontaktem lub zakupem.',
    focus: 0.78,
  },
  {
    id: 'ads',
    label: 'Reklamy są coraz droższe',
    short: 'Droższe reklamy',
    description: 'Płacisz coraz więcej za pozyskanie klienta i nie wiesz, czy problem leży w reklamach, stronie, ofercie czy dalszej części sprzedaży.',
    focus: 0.38,
  },
  {
    id: 'website',
    label: 'Strona nie sprzedaje',
    short: 'Strona nie sprzedaje',
    description: 'Masz stronę i ruch, ale nie przekładają się na wystarczającą liczbę zapytań lub sprzedaży.',
    focus: 0.56,
  },
  {
    id: 'competition',
    label: 'Konkurencja mnie wyprzedza',
    short: 'Konkurencja',
    description: 'Konkurenci są bardziej widoczni albo częściej wybierani. Chcesz wiedzieć, co robią lepiej i gdzie możesz odzyskać przewagę.',
    focus: 0.47,
  },
  {
    id: 'unclear',
    label: 'Nie wiem, od czego zacząć',
    short: 'Nie wiem, od czego zacząć',
    description: 'SEO, reklamy, media społecznościowe, strona, oferta… każdy proponuje coś innego. Potrzebujesz ustalić, co naprawdę powinno być pierwsze.',
    focus: 0.62,
  },
  {
    id: 'other',
    label: 'Inny problem',
    short: 'Inny problem',
    description: 'Możesz opisać sytuację własnymi słowami. Nie musisz dopasowywać problemu do nazwy usługi.',
    focus: 0.62,
  },
]

export const processSteps = [
  {
    no: '01',
    title: 'Pokazujesz nam firmę',
    accent: 'firmę',
    copy: 'Na start wystarczy strona i krótki opis sytuacji. Jeśli masz dane z GA4, Google, reklam lub CRM — wykorzystamy je tam, gdzie pomagają podjąć pewniejszą decyzję.',
  },
  {
    no: '02',
    title: 'Sprawdzamy, gdzie tracisz klientów',
    accent: 'tracisz klientów',
    copy: 'Analizujemy drogę od znalezienia firmy do kontaktu lub zakupu. Sprawdzamy m.in. widoczność, ofertę, stronę, zaufanie, kanały pozyskania i konwersję.',
  },
  {
    no: '03',
    title: 'Ustalamy, co jest najważniejsze',
    accent: 'najważniejsze',
    copy: 'Nie dostajesz listy 30 rzeczy do poprawy. Wskazujemy, co dziś najbardziej ogranicza wynik i które działania powinny mieć pierwszeństwo.',
  },
  {
    no: '04',
    title: 'Dostajesz plan działania',
    accent: 'plan działania',
    copy: 'Wiesz, co zrobić teraz, co później, czego na razie nie ruszać i po czym poznać, że zmiana działa.',
  },
]

export const diagnosis = {
  problem: 'Oferta i ścieżka kontaktu nie wykorzystują istniejącego ruchu.',
  summary: 'Ruch już dociera na stronę, ale klient nie dostaje wystarczająco jasnego powodu do wyboru ani wystarczająco prostej drogi do kontaktu.',
  evidence: [
    {
      label: 'Obserwacja',
      value: 'Za mało osób przechodzi od wejścia na stronę do kontaktu.',
      detail: 'Ruch istnieje, więc dokładanie kolejnych wejść nie rozwiązuje głównego ograniczenia. Największa strata pojawia się później — między zainteresowaniem a kontaktem.',
      confidence: 'POTWIERDZONE',
    },
    {
      label: 'Znaczenie',
      value: 'Oferta, wezwanie do działania i formularz tworzą niepotrzebne tarcie.',
      detail: 'Najważniejsza wartość jest komunikowana zbyt późno, wezwanie do działania nie wskazuje jasno następnego kroku, a formularz wymaga decyzji zanim klient rozumie, co dostanie.',
      confidence: 'SILNY SYGNAŁ',
    },
    {
      label: 'Priorytet',
      value: 'Najpierw uprościć ofertę i ścieżkę konwersji.',
      detail: 'To ruch, który pozwala lepiej wykorzystać popyt już obecny. Dopiero po tej zmianie warto oceniać, czy potrzebne jest zwiększanie ruchu.',
      confidence: 'SILNY SYGNAŁ',
    },
  ],
  stages: [
    { name: 'Widoczność', status: 'Wystarczająca', score: '72%', note: 'Firma jest znajdowana. To nie tutaj dziś znika największa część potencjału.' },
    { name: 'Strona i oferta', status: 'Do poprawy', score: '54%', note: 'Wartość jest obecna, ale klient musi zbyt długo szukać powodu do wyboru.' },
    { name: 'Media społecznościowe i treści', status: 'Wspierające', score: '63%', note: 'Treści pomagają budować kontekst, ale nie domykają głównego problemu.' },
    { name: 'Zaufanie', status: 'Silny sygnał', score: '58%', note: 'Dowody zaufania są obecne, lecz pojawia się za późno i nie pracuje wystarczająco mocno na decyzję.' },
    { name: 'Konwersja', status: 'Wąskie gardło', score: '31%', note: 'Największa strata następuje między zrozumieniem oferty a rozpoczęciem kontaktu.' },
  ],
  plan: [
    { no: '01', title: 'Wyostrzyć ofertę', copy: 'Nazwać rezultat, odbiorcę i powód wyboru już w pierwszym ekranie.' },
    { no: '02', title: 'Uprościć następny krok', copy: 'Zostawić jedno główne wezwanie do działania na kluczowych ekranach zamiast kilku równorzędnych ścieżek.' },
    { no: '03', title: 'Zmniejszyć tarcie', copy: 'Skrócić formularz i zbierać na początku tylko informacje potrzebne do pierwszego kontaktu.' },
    { no: '04', title: 'Sprawdzić efekt', copy: 'Porównać współczynnik przejścia do kontaktu i liczbę jakościowych zapytań przed i po zmianie.' },
  ],
  decision: 'Najpierw poprawić ofertę i ścieżkę kontaktu. Zwiększanie ruchu ma sens dopiero wtedy, gdy obecny ruch jest lepiej wykorzystywany.',
  doNow: 'Przenieść główną przewagę i jedno wyraźne wezwanie do działania w pierwszym ekranie, a następnie skrócić drogę do kontaktu.',
  notNow: 'Nie zwiększać jeszcze budżetu Reklamy Google i nie rozpoczynać pełnej przebudowy strony.',
  measure: 'Współczynnik przejścia do kontaktu, liczba jakościowych zapytań oraz koszt pozyskania zapytania.',
}

export const toolGroups = [
  {
    id: 'data',
    no: '01',
    title: 'Dane i zachowanie',
    copy: 'Co użytkownicy faktycznie robią i gdzie kończy się ich droga.',
    tools: [
      { code: 'GA4', name: 'Google Analytics 4', detail: 'Ruch, zachowanie, konwersje i punkty odpływu.' },
      { code: 'GSC', name: 'Google Search Console', detail: 'Zapytania, strony wejścia, widoczność i problemy indeksacji.' },
    ],
  },
  {
    id: 'visibility',
    no: '02',
    title: 'Widoczność i rynek',
    copy: 'Gdzie firma jest obecna, gdzie znika i jak wygląda na tle realnej konkurencji.',
    tools: [
      { code: 'SF', name: 'Screaming Frog', detail: 'Architektura, analiza indeksowania, techniczne SEO i jakość struktury serwisu.' },
      { code: 'AH', name: 'Ahrefs', detail: 'Konkurencja, linki, tematy i różnice w widoczności.' },
      { code: 'GBP', name: 'Profil Firmy w Google', detail: 'Lokalność, opinie, kategorie i pozycja obok konkurencji.' },
    ],
  },
  {
    id: 'acquisition',
    no: '03',
    title: 'Płatne pozyskanie',
    copy: 'Czy budżet prowadzi do właściwego ruchu, jakościowych zapytań i sprzedaży.',
    tools: [
      { code: 'GADS', name: 'Reklamy Google', detail: 'Intencja, koszt, jakość ruchu i skuteczność kampanii.' },
      { code: 'META', name: 'Reklamy Meta', detail: 'Kreacje, odbiorcy, przepływ zapytań i jakość pozyskania.' },
    ],
  },
  {
    id: 'ai',
    no: '04',
    title: 'Wyszukiwanie AI i automatyzacja',
    copy: 'Jak marka pojawia się w nowych sposobach wyszukiwania i gdzie automatyzacja faktycznie ma sens.',
    tools: [
      { code: 'AI', name: 'ChatGPT / Gemini / Claude', detail: 'Widoczność marki, badanie, synteza i porównanie źródeł.' },
      { code: 'N8N', name: 'n8n', detail: 'Automatyzacja powtarzalnych przepływów tam, gdzie rzeczywiście skraca pracę.' },
    ],
  },
]

export const industries = [
  { name: 'Medycyna Estetyczna', tag: 'Usługi + Zaufanie' },
  { name: 'Stomatologia', tag: 'Lokalność + Decyzja' },
  { name: 'Uroda', tag: 'Media Społecznościowe + Lokalność' },
  { name: 'Nieruchomości', tag: 'Pozyskiwanie Klientów' },
  { name: 'Kancelarie', tag: 'Eksperckość + Zaufanie' },
  { name: 'Usługi Lokalne', tag: 'Google + Konwersja' },
  { name: 'Handel Internetowy', tag: 'Ruch + Konwersja' },
  { name: 'SaaS i Produkty Cyfrowe', tag: 'Produkt + Pozyskanie' },
  { name: 'Eksperci i Edukacja', tag: 'Autorytet + Zapytania' },
  { name: 'Hotele i Gastronomia', tag: 'Lokalność + Rezerwacje' },
  { name: 'Motoryzacja', tag: 'Lokalność + Zapytania' },
  { name: 'Usługi B2B', tag: 'Proces Sprzedaży + Pozycjonowanie' },
]

export const projects = [
  {
    index: '01',
    name: 'CostWarden',
    type: 'SaaS AI / Produkt / Strona Internetowa',
    status: 'PRZED PREMIERĄ',
    scope: 'Strona Docelowa · Strategia Produktu · Pozycjonowanie · UX/UI · Wejście na Rynek',
    problem: 'Przełożyć złożony produkt AI na prostą propozycję wartości i czytelną ścieżkę wejścia na rynek.',
    role: 'Pozycjonowanie produktu, architektura informacji, UX/UI i komunikacja strony docelowej.',
    result: 'Projekt przed premierą — bez deklarowania wyników przed publikacją.',
    description: 'Produkt SaaS przygotowywany od pozycjonowania i architektury informacji po doświadczenie strony i komunikację wejścia na rynek.',
    url: '',
    image: '',
  },
  {
    index: '02',
    name: 'GymWrld',
    type: 'Aplikacja Fitness / UX Produktu',
    status: 'W TRAKCIE ROZWOJU',
    scope: 'Kierunek Produktu · UX · Grywalizacja',
    problem: 'Uporządkować doświadczenie produktu i mechaniki, które mają zachęcać użytkownika do regularnego powrotu.',
    role: 'Kierunek produktu, UX i koncepcja mechanik zaangażowania.',
    result: 'Projekt w trakcie rozwoju — pokazujemy zakres i status, nie wymyślamy KPI.',
    description: 'Kierunek produktu i doświadczenia aplikacji fitness, z naciskiem na mechaniki zaangażowania i czytelną ścieżkę użytkownika.',
    url: '',
    image: '',
  },
  {
    index: '03',
    name: 'Anna Bagrowska / Psycholog',
    type: 'Strona Internetowa / UX / SEO',
    status: 'W REALIZACJI',
    scope: 'Strona Internetowa V2 · Treść · Układ · SEO',
    problem: 'Uprościć komunikację eksperckiej oferty i ułatwić użytkownikowi zrozumienie kolejnego kroku.',
    role: 'Treść, struktura informacji, UX, układ i fundament pod widoczność organiczną.',
    result: 'Projekt w realizacji — finalny rezultat będzie można ocenić po publikacji.',
    description: 'Przebudowa strony eksperckiej: komunikacja oferty, struktura treści, UX oraz fundament pod widoczność organiczną.',
    url: '',
    image: '',
  },
  {
    index: '04',
    name: 'Do Poznania',
    type: 'Strona Docelowa / Przepływ Zapytań',
    status: 'PRZED PUBLIKACJĄ',
    scope: 'Strona Docelowa · Formularz · Skrzynka Odbiorcza · Przepływ Zapytań',
    problem: 'Zbudować prostą drogę od wejścia na stronę docelową do wysłania zapytania.',
    role: 'Strona docelowa, formularz, obsługa kontaktu i przepływ zapytań.',
    result: 'Projekt przygotowany do finalnej weryfikacji przed publikacją.',
    description: 'Strona docelowa z prostą ścieżką kontaktu i obsługą formularza, przygotowany do finalnej weryfikacji przed publikacją.',
    url: '',
    image: '',
  },
]

export const team = {
  members: [
    {
      initials: 'A',
      name: 'Artur',
      role: 'Założyciel',
      bio: 'Kierunek firmy, perspektywa biznesowa i odpowiedzialność za to, żeby końcowa rekomendacja prowadziła do konkretnej decyzji.',
      photo: '',
      featured: true,
    },
    {
      initials: 'K',
      name: 'Kari',
      role: 'Dyrektorka Marketingu',
      bio: 'Strategia marketingowa, pozycjonowanie, komunikacja i ocena całej drogi klienta od pierwszego kontaktu z marką do decyzji.',
      photo: '',
    },
    {
      initials: 'R',
      name: 'Roman',
      role: 'Rozwój Stron i Techniczne SEO',
      bio: 'Warstwa techniczna stron, rozwój techniczny, wydajność i techniczne SEO — czyli miejsca, w których ograniczenie może wynikać z samego produktu cyfrowego.',
      photo: '',
    },
    {
      initials: 'G',
      name: 'Gerard',
      role: 'Specjalista Reklam Płatnych',
      bio: 'Płatne pozyskanie, jakość ruchu, koszt i ocena, czy budżet reklamowy prowadzi do właściwych zapytań i sprzedaży.',
      photo: '',
    },
    {
      initials: 'A',
      name: 'Anna',
      role: 'Menedżerka Mediów Społecznościowych',
      bio: 'Media społecznościowe i treści z perspektywy zaufania, spójności marki i tego, czy treści pomagają klientowi przejść do kolejnego kroku.',
      photo: '',
    },
  ],
}

export const offers = [
  {
    id: 'mini',
    code: '01',
    label: 'Pierwszy sygnał',
    name: 'Mini Mapa',
    price: '0 zł',
    audience: 'Firma, która wie, że coś nie działa, ale nie wie jeszcze, gdzie zacząć.',
    bestFor: 'Gdy chcesz najpierw sprawdzić kierunek bez kupowania pełnej diagnozy.',
    copy: 'Krótki pierwszy obraz sytuacji, który wskazuje, któremu obszarowi warto przyjrzeć się jako pierwszemu.',
    includes: ['Pierwsze Sygnały', 'Potencjalne Ograniczenie', 'Kierunek Dalszej Diagnozy'],
    result: 'Wiesz, któremu obszarowi warto przyjrzeć się jako pierwszemu.',
    cta: 'Zacznij bezpłatnie',
  },
  {
    id: 'start',
    code: '02',
    label: 'Jeden problem. Jeden priorytet.',
    name: 'Mapa Podstawowa',
    price: '249 zł',
    audience: 'Firma z konkretnym problemem, która nie potrzebuje jeszcze analizy całego procesu.',
    bestFor: 'Gdy chcesz ustalić jeden główny problem i pierwszy ruch.',
    copy: 'Krótsza diagnoza skupiona na jednym ograniczeniu zamiast analizowania wszystkiego naraz.',
    includes: ['Problem #1', 'Najważniejsze Dowody', 'Pierwszy Ruch', 'Lista „Nie Teraz”'],
    result: 'Wiesz, co zrobić najpierw i czego obecnie nie ruszać.',
    cta: 'Wybieram Mapę Podstawową',
  },
  {
    id: 'strategic',
    code: '03',
    label: 'Pełna diagnoza procesu pozyskiwania klienta',
    name: 'Mapa Strategiczna',
    price: '499 zł',
    audience: 'Firma, w której działa kilka kanałów, problemy się nakładają albo budżet jest rozproszony.',
    bestFor: 'Gdy trudno wskazać jeden oczywisty problem i potrzebujesz uporządkować decyzje przed kolejnym większym wydatkiem.',
    copy: 'Pełna diagnoza drogi klienta — od widoczności i oferty po zaufanie, konwersję i kolejność następnych działań.',
    includes: ['Diagnoza Obecnej Sytuacji', 'Mapa Drogi Klienta', 'Najważniejsze Ograniczenie', 'Dowody i Poziom Pewności', 'Priorytety Krok po Kroku', 'Lista „Nie Teraz”', 'Plan Działania', 'KPI / Mierniki', '60-minutowa Konsultacja Strategiczna'],
    result: 'Wiesz, co robić teraz, co zrobić następnie, czego nie robić, gdzie skierować czas i budżet oraz co mierzyć.',
    cta: 'Zamów Mapę Strategiczną',
    featured: true,
    anchor: '499 zł za lepszą decyzję przed znacznie większym wydatkiem.',
  },
  {
    id: 'ai',
    code: '04',
    label: 'Widoczność w AI',
    name: 'Mapa AI',
    price: '199 zł',
    audience: 'Firma, która chce sprawdzić, jak jest widoczna i przedstawiana w systemach AI.',
    bestFor: 'Gdy interesuje Cię konkretnie obecność marki w ChatGPT, Gemini i Claude.',
    copy: 'Sprawdzamy próbę widoczności marki w odpowiednich scenariuszach wyszukiwania i to, jak systemy AI opisują firmę.',
    includes: ['Próba Widoczności', 'Sposób Przedstawiania Marki', 'Luki Informacyjne', 'Rekomendacje Poprawy'],
    result: 'Wiesz, jak AI przedstawia firmę, gdzie są braki i co można poprawić — bez obiecywania pozornej precyzji „AI SEO”.',
    cta: 'Sprawdź AI',
  },
  {
    id: 'implementation',
    code: '05',
    label: 'Po diagnozie',
    name: 'Wdrożenie / Monitorowanie',
    price: 'Indywidualnie',
    audience: 'Firma, która ma już ustalony priorytet i chce przejść do działania albo pomiaru.',
    bestFor: 'Gdy Mapa pokazała problem wymagający wdrożenia lub późniejszego monitorowania.',
    copy: 'Zakres i wycena wynikają z diagnozy. Nie sprzedajemy rozwiązania na zapas.',
    includes: ['Wdrożenie Ustalonego Priorytetu', 'Pomiar Efektu', 'Monitorowanie Zmian', 'Kolejna Decyzja, Gdy Dane To Uzasadniają'],
    result: 'Możesz wdrożyć rekomendacje samodzielnie, z własnym zespołem, obecnym wykonawcą albo z DigitalMap.',
    cta: 'Zapytaj o zakres',
  },
]

export const faqs = [
  {
    q: 'Czy DigitalMap jest dla firmy, która dopiero zaczyna?',
    a: 'Tak, jeśli istnieje już rynek, oferta lub pierwsze sygnały, które można ocenić. Przy bardzo wczesnym etapie możemy też powiedzieć wprost, że pełna diagnoza byłaby jeszcze przedwczesna i zacząć od Mini Mapy.',
  },
  {
    q: 'Mam już agencję, niezależnego specjalistę albo własny zespół marketingowy — czy Mapa ma sens?',
    a: 'Tak. DigitalMap może być niezależnym drugim spojrzeniem na obecne działania: co dziś jest priorytetem, czego może brakować, które założenia warto zweryfikować i jakie pytania warto zadać wykonawcy lub zespołowi.',
  },
  {
    q: 'Czy będziecie później próbowali sprzedać mi wdrożenie?',
    a: 'Wdrożenie jest opcją, nie warunkiem. Najpierw kończymy diagnozę. Jeśli wynik pokaże, że potrzebne jest konkretne wdrożenie, możemy przygotować zakres — ale rekomendację możesz zrealizować również poza DigitalMap.',
  },
  {
    q: 'Czy muszę później korzystać z DigitalMap?',
    a: 'Nie. Rekomendacje możesz wdrożyć samodzielnie, z własnym zespołem, obecną agencją, niezależnym specjalistą albo innym wykonawcą.',
  },
  {
    q: 'Czym Mapa różni się od klasycznego audytu?',
    a: 'Klasyczny audyt często kończy się listą rzeczy do poprawy. Mapa ma ustalić kolejność: co jest najważniejszym ograniczeniem, jakie dowody za tym stoją, co zrobić teraz, czego nie ruszać i co mierzyć.',
  },
  {
    q: 'Czy otrzymam gotową strategię?',
    a: 'Otrzymujesz diagnozę, priorytety, plan następnych ruchów i mierniki. To nie jest automatycznie pełna strategia wykonawcza dla każdego kanału — jej zakres wynika dopiero z tego, co diagnoza pokaże jako priorytet.',
  },
  {
    q: 'Jak długo trwa przygotowanie?',
    a: 'Termin zależy od wybranego zakresu i dostępnych danych. Potwierdzamy go przed startem, zamiast obiecywać sztucznego terminu gwarantowanego, którego nie da się konsekwentnie utrzymać.',
  },
  {
    q: 'Jakie dane muszę przekazać?',
    a: 'Na start wystarczy domena lub nazwa firmy i krótki kontekst. Jeśli masz GA4, Google Search Console, dane z kampanii, CRM lub inne źródła, możemy je wykorzystać tam, gdzie zwiększają pewność diagnozy.',
  },
  {
    q: 'Co jeśli nie mam GA4 albo Google Search Console?',
    a: 'To nie blokuje startu. Możemy zacząć od publicznie dostępnych danych, rynku, widoczności, komunikacji i ścieżki klienta. Poziom pewności wniosków pokazujemy wprost.',
  },
  {
    q: 'Czy analizujecie SEO, reklamy, media społecznościowe i stronę?',
    a: 'Tak — jako elementy całej drogi klienta. Nie zakładamy jednak z góry, że któryś z tych kanałów jest problemem albo rozwiązaniem.',
  },
  {
    q: 'Czy konsultacja jest w cenie Mapy Strategicznej?',
    a: 'Tak. Mapa Strategiczna obejmuje 60-minutową konsultację, podczas której omawiamy diagnozę, rekomendacje, pytania i najbliższe decyzje.',
  },
  {
    q: 'W jakiej formie dostanę Mapę?',
    a: 'Dostajesz uporządkowaną Mapę diagnozy: problem, dowody, poziom pewności, priorytety, plan działania, rzeczy „nie teraz” i mierniki. Nie zostajesz z samą listą błędów.',
  },
  {
    q: 'Co jeśli chcę wdrożyć rekomendacje samodzielnie?',
    a: 'Możesz. Diagnoza nie wiąże Cię z DigitalMap ani z konkretnym wykonawcą.',
  },
]
