export const symptoms = [
  {
    id: 'acquisition',
    label: 'Za mało klientów',
    short: 'Za mało klientów',
    description: 'Robisz marketing, ale liczba zapytań lub sprzedaży nadal jest za mała. Chcesz wiedzieć, co faktycznie warto poprawić.',
    focus: 0.24,
  },
  {
    id: 'conversion',
    label: 'Dużo ruchu, mało zapytań',
    short: 'Mało zapytań',
    description: 'Ludzie wchodzą na stronę, ale niewielu robi kolejny krok. Sprawdzimy, co zatrzymuje ich przed kontaktem lub zakupem.',
    focus: 0.78,
  },
  {
    id: 'ads',
    label: 'Reklamy są coraz droższe',
    short: 'Droższe reklamy',
    description: 'Płacisz coraz więcej za pozyskanie klienta i nie wiesz, czy problem leży w reklamach, stronie, ofercie czy dalszej części sprzedaży.',
    focus: 0.38,
  },
  {
    id: 'website',
    label: 'Strona nie sprzedaje',
    short: 'Strona nie sprzedaje',
    description: 'Masz stronę i ruch, ale nie przekładają się na wystarczającą liczbę zapytań lub sprzedaży.',
    focus: 0.56,
  },
  {
    id: 'competition',
    label: 'Konkurencja mnie wyprzedza',
    short: 'Konkurencja',
    description: 'Konkurenci są bardziej widoczni albo częściej wybierani. Chcesz wiedzieć, co robią lepiej i gdzie możesz odzyskać przewagę.',
    focus: 0.47,
  },
  {
    id: 'unclear',
    label: 'Nie wiem, od czego zacząć',
    short: 'Nie wiem, od czego zacząć',
    description: 'SEO, reklamy, social media, strona, oferta… każdy proponuje coś innego. Potrzebujesz ustalić, co naprawdę powinno być pierwsze.',
    focus: 0.62,
  },
  {
    id: 'other',
    label: 'Inny problem',
    short: 'Inny problem',
    description: 'Możesz opisać sytuację własnymi słowami. Nie musisz dopasowywać problemu do nazwy usługi.',
    focus: 0.62,
  },
]

export const processSteps = [
  {
    no: '01',
    title: 'Zaczynamy od Twojej sytuacji',
    accent: 'Twojej sytuacji',
    copy: 'Na start wystarczy strona i krótki opis tego, co dziś nie działa tak, jak powinno. Jeśli masz dane z Google, Analytics, reklam lub CRM, wykorzystamy je, żeby lepiej zrozumieć sytuację.',
  },
  {
    no: '02',
    title: 'Sprawdzamy, gdzie tracisz klientów',
    accent: 'tracisz klientów',
    copy: 'Analizujemy drogę od znalezienia firmy do kontaktu lub zakupu i szukamy miejsc, które mogą wpływać na decyzję klienta.',
  },
  {
    no: '03',
    title: 'Ustalamy, co jest najważniejsze',
    accent: 'najważniejsze',
    copy: 'Nie dostajesz listy 30 rzeczy do poprawy. Wskazujemy, co dziś najbardziej ogranicza wynik i co powinno mieć pierwszeństwo.',
  },
  {
    no: '04',
    title: 'Dostajesz plan działania',
    accent: 'plan działania',
    copy: 'Wiesz, co zrobić teraz, co później, czego na razie nie ruszać i po czym poznać, że zmiana działa.',
  },
]

export const diagnosis = {
  problem: 'Oferta i ścieżka kontaktu nie wykorzystują istniejącego ruchu.',
  summary: 'Ruch już dociera na stronę, ale klient nie dostaje wystarczająco jasnego powodu do wyboru ani wystarczająco prostej drogi do kontaktu.',
  evidence: [
    {
      label: 'Obserwacja',
      value: 'Za mało osób przechodzi od wejścia na stronę do kontaktu.',
      detail: 'Ruch istnieje, więc dokładanie kolejnych wejść nie rozwiązuje głównego ograniczenia. Największa strata pojawia się później — między zainteresowaniem a kontaktem.',
      confidence: 'POTWIERDZONE',
    },
    {
      label: 'Znaczenie',
      value: 'Oferta, wezwanie do działania i formularz tworzą niepotrzebne tarcie.',
      detail: 'Najważniejsza wartość jest komunikowana zbyt późno, wezwanie do działania nie wskazuje jasno następnego kroku, a formularz wymaga decyzji zanim klient rozumie, co dostanie.',
      confidence: 'SILNY SYGNAŁ',
    },
    {
      label: 'Priorytet',
      value: 'Najpierw uprościć ofertę i ścieżkę konwersji.',
      detail: 'To ruch, który pozwala lepiej wykorzystać popyt już obecny. Dopiero po tej zmianie warto oceniać, czy potrzebne jest zwiększanie ruchu.',
      confidence: 'SILNY SYGNAŁ',
    },
  ],
  stages: [
    { name: 'Widoczność', status: 'Wystarczająca', score: '72%', note: 'Firma jest znajdowana. To nie tutaj dziś znika największa część potencjału.' },
    { name: 'Strona i oferta', status: 'Do poprawy', score: '54%', note: 'Wartość jest obecna, ale klient musi zbyt długo szukać powodu do wyboru.' },
    { name: 'Social Media i Treści', status: 'Wspierające', score: '63%', note: 'Treści pomagają budować kontekst, ale nie domykają głównego problemu.' },
    { name: 'Zaufanie', status: 'Silny sygnał', score: '58%', note: 'Dowody zaufania są obecne, lecz pojawia się za późno i nie pracuje wystarczająco mocno na decyzję.' },
    { name: 'Konwersja', status: 'Wąskie gardło', score: '31%', note: 'Największa strata następuje między zrozumieniem oferty a rozpoczęciem kontaktu.' },
  ],
  plan: [
    { no: '01', title: 'Wyostrzyć ofertę', copy: 'Nazwać rezultat, odbiorcę i powód wyboru już w pierwszym ekranie.' },
    { no: '02', title: 'Uprościć następny krok', copy: 'Zostawić jedno główne wezwanie do działania na kluczowych ekranach zamiast kilku równorzędnych ścieżek.' },
    { no: '03', title: 'Zmniejszyć tarcie', copy: 'Skrócić formularz i zbierać na początku tylko informacje potrzebne do pierwszego kontaktu.' },
    { no: '04', title: 'Sprawdzić efekt', copy: 'Porównać współczynnik przejścia do kontaktu i liczbę jakościowych zapytań przed i po zmianie.' },
  ],
  decision: 'Najpierw poprawić ofertę i ścieżkę kontaktu. Zwiększanie ruchu ma sens dopiero wtedy, gdy obecny ruch jest lepiej wykorzystywany.',
  doNow: 'Przenieść główną przewagę i jedno wyraźne wezwanie do działania w pierwszym ekranie, a następnie skrócić drogę do kontaktu.',
  notNow: 'Nie zwiększać jeszcze budżetu Reklamy Google i nie rozpoczynać pełnej przebudowy strony.',
  measure: 'Współczynnik przejścia do kontaktu, liczba jakościowych zapytań oraz koszt pozyskania zapytania.',
}

export const toolGroups = [
  {
    id: 'data',
    no: '01',
    title: 'Dane i zachowanie',
    copy: 'Co użytkownicy faktycznie robią i gdzie kończy się ich droga.',
    tools: [
      { code: 'GA4', name: 'Google Analytics 4', detail: 'Ruch, zachowanie, konwersje i punkty odpływu.' },
      { code: 'GSC', name: 'Google Search Console', detail: 'Zapytania, strony wejścia, widoczność i problemy indeksacji.' },
    ],
  },
  {
    id: 'visibility',
    no: '02',
    title: 'Widoczność i rynek',
    copy: 'Gdzie firma jest obecna, gdzie znika i jak wygląda na tle realnej konkurencji.',
    tools: [
      { code: 'SF', name: 'Screaming Frog', detail: 'Architektura, analiza indeksowania, techniczne SEO i jakość struktury serwisu.' },
      { code: 'AH', name: 'Ahrefs', detail: 'Konkurencja, linki, tematy i różnice w widoczności.' },
      { code: 'GBP', name: 'Profil Firmy w Google', detail: 'Lokalność, opinie, kategorie i pozycja obok konkurencji.' },
    ],
  },
  {
    id: 'acquisition',
    no: '03',
    title: 'Płatne pozyskanie',
    copy: 'Czy budżet prowadzi do właściwego ruchu, jakościowych zapytań i sprzedaży.',
    tools: [
      { code: 'GADS', name: 'Reklamy Google', detail: 'Intencja, koszt, jakość ruchu i skuteczność kampanii.' },
      { code: 'META', name: 'Reklamy Meta', detail: 'Kreacje, odbiorcy, przepływ zapytań i jakość pozyskania.' },
    ],
  },
  {
    id: 'ai',
    no: '04',
    title: 'Wyszukiwanie AI i automatyzacja',
    copy: 'Jak marka pojawia się w nowych sposobach wyszukiwania i gdzie automatyzacja faktycznie ma sens.',
    tools: [
      { code: 'AI', name: 'ChatGPT / Gemini / Claude', detail: 'Widoczność marki, badanie, synteza i porównanie źródeł.' },
      { code: 'N8N', name: 'n8n', detail: 'Automatyzacja powtarzalnych przepływów tam, gdzie rzeczywiście skraca pracę.' },
    ],
  },
]

export const industries = [
  { name: 'Kliniki i medycyna estetyczna', decision: 'Czy klient widzi wystarczająco dużo konkretu i zaufania, żeby umówić konsultację zamiast wrócić do porównywania klinik?' },
  { name: 'Stomatologia', decision: 'Czy lokalna widoczność, opinie i oferta prowadzą pacjenta od wyszukania usługi do umówienia wizyty?' },
  { name: 'Beauty i wellness', decision: 'Czy zainteresowanie budowane w social media i lokalnie zamienia się w rezerwację, a nie kończy na obserwowaniu profilu?' },
  { name: 'Nieruchomości', decision: 'Czy prezentacja oferty i sposób kontaktu dają klientowi wystarczający powód, żeby wysłać zapytanie właśnie do Ciebie?' },
  { name: 'Prawo', decision: 'Czy eksperckość i wiarygodność są czytelne na tyle szybko, żeby klient zdecydował się na pierwszy kontakt?' },
  { name: 'Usługi lokalne', decision: 'Czy klient może szybko Cię znaleźć, zrozumieć ofertę i przejść do kontaktu bez niepotrzebnego tarcia?' },
  { name: 'E-commerce', decision: 'Czy ruch przechodzi płynnie od produktu do koszyka i zakupu, czy tracisz sprzedaż na którymś etapie?' },
  { name: 'SaaS i produkty cyfrowe', decision: 'Czy użytkownik rozumie wartość produktu wystarczająco szybko, żeby przejść do demo, wersji próbnej lub zakupu?' },
  { name: 'Eksperci i firmy usługowe', decision: 'Czy marka pokazuje wartość i wiarygodność zanim klient zacznie porównywać głównie cenę?' },
  { name: 'Hotele i gastronomia', decision: 'Czy widoczność, opinie i oferta prowadzą od znalezienia miejsca do rezerwacji bez zbędnych kroków?' },
  { name: 'Motoryzacja', decision: 'Czy po znalezieniu firmy klient od razu wie, dlaczego warto zadzwonić, umówić wizytę lub wysłać zapytanie?' },
  { name: 'B2B', decision: 'Czy strona i komunikacja pomagają osobie decyzyjnej szybko zrozumieć wartość i przejść do rozmowy?' },
]

export const projects = [
  {
    index: '01',
    name: 'CostWarden',
    type: 'SaaS AI / Produkt / Strona Internetowa',
    status: 'PRZED PREMIERĄ',
    scope: 'Strona Docelowa · Strategia Produktu · Pozycjonowanie · UX/UI · Wejście na Rynek',
    problem: 'Przełożyć złożony produkt AI na prostą propozycję wartości i czytelną ścieżkę wejścia na rynek.',
    role: 'Pozycjonowanie produktu, architektura informacji, UX/UI i komunikacja strony docelowej.',
    result: 'Projekt przed premierą — bez deklarowania wyników przed publikacją.',
    description: 'Produkt SaaS przygotowywany od pozycjonowania i architektury informacji po doświadczenie strony i komunikację wejścia na rynek.',
    url: '',
    image: '',
  },
  {
    index: '02',
    name: 'GymWrld',
    type: 'Aplikacja Fitness / UX Produktu',
    status: 'W TRAKCIE ROZWOJU',
    scope: 'Kierunek Produktu · UX · Grywalizacja',
    problem: 'Uporządkować doświadczenie produktu i mechaniki, które mają zachęcać użytkownika do regularnego powrotu.',
    role: 'Kierunek produktu, UX i koncepcja mechanik zaangażowania.',
    result: 'Projekt w trakcie rozwoju — pokazujemy zakres i status, nie wymyślamy KPI.',
    description: 'Kierunek produktu i doświadczenia aplikacji fitness, z naciskiem na mechaniki zaangażowania i czytelną ścieżkę użytkownika.',
    url: '',
    image: '',
  },
  {
    index: '03',
    name: 'Anna Bagrowska / Psycholog',
    type: 'Strona Internetowa / UX / SEO',
    status: 'W REALIZACJI',
    scope: 'Strona Internetowa V2 · Treść · Układ · SEO',
    problem: 'Uprościć komunikację eksperckiej oferty i ułatwić użytkownikowi zrozumienie kolejnego kroku.',
    role: 'Treść, struktura informacji, UX, układ i fundament pod widoczność organiczną.',
    result: 'Projekt w realizacji — finalny rezultat będzie można ocenić po publikacji.',
    description: 'Przebudowa strony eksperckiej: komunikacja oferty, struktura treści, UX oraz fundament pod widoczność organiczną.',
    url: '',
    image: '',
  },
  {
    index: '04',
    name: 'Do Poznania',
    type: 'Strona Docelowa / Przepływ Zapytań',
    status: 'PRZED PUBLIKACJĄ',
    scope: 'Strona Docelowa · Formularz · Skrzynka Odbiorcza · Przepływ Zapytań',
    problem: 'Zbudować prostą drogę od wejścia na stronę docelową do wysłania zapytania.',
    role: 'Strona docelowa, formularz, obsługa kontaktu i przepływ zapytań.',
    result: 'Projekt przygotowany do finalnej weryfikacji przed publikacją.',
    description: 'Strona docelowa z prostą ścieżką kontaktu i obsługą formularza, przygotowany do finalnej weryfikacji przed publikacją.',
    url: '',
    image: '',
  },
]

export const team = {
  members: [
    {
      initials: 'B',
      name: 'Bartosz',
      role: 'Founder',
      bio: 'Kierunek firmy, perspektywa biznesowa i odpowiedzialność za to, żeby końcowa rekomendacja prowadziła do konkretnej decyzji.',
      photo: '',
      featured: true,
    },
    {
      initials: 'K',
      name: 'Kasia',
      role: 'Marketing',
      bio: 'Strategia marketingowa, pozycjonowanie, komunikacja i ocena całej drogi klienta od pierwszego kontaktu z marką do decyzji.',
      photo: '',
    },
    {
      initials: 'O',
      name: 'Oliwia',
      role: 'Marketing',
      bio: 'Warstwa techniczna stron, rozwój techniczny, wydajność i techniczne SEO — czyli miejsca, w których ograniczenie może wynikać z samego produktu cyfrowego.',
      photo: '',
    },
      {
      initials: 'P',
      name: 'Paulina',
      role: 'Marketing',
      bio: 'Warstwa techniczna stron, rozwój techniczny, wydajność i techniczne SEO — czyli miejsca, w których ograniczenie może wynikać z samego produktu cyfrowego.',
      photo: '',
    },
    {
      initials: 'M',
      name: 'Michał',
      role: 'Web Development | Tech SEO',
      bio: 'Warstwa techniczna stron, rozwój techniczny, wydajność i techniczne SEO — czyli miejsca, w których ograniczenie może wynikać z samego produktu cyfrowego.',
      photo: '',
    },
    {
      initials: 'M',
      name: 'Kacper',
      role: 'Web Development | UX, UI',
      bio: 'Warstwa techniczna stron, rozwój techniczny, wydajność i techniczne SEO — czyli miejsca, w których ograniczenie może wynikać z samego produktu cyfrowego.',
      photo: '',
    },
    {
      initials: 'N',
      name: 'Natalia',
      role: 'PPC Specialist',
      bio: 'Płatne pozyskanie, jakość ruchu, koszt i ocena, czy budżet reklamowy prowadzi do właściwych zapytań i sprzedaży.',
      photo: '',
    },
    {
      initials: 'P',
      name: 'Paulina',
      role: 'Social Media Manager',
      bio: 'Social media i treści z perspektywy zaufania, spójności marki i tego, czy treści pomagają klientowi przejść do kolejnego kroku.',
      photo: '',
    },
  ],
}

export const offers = [
  {
    id: 'mini',
    code: '01',
    name: 'Mini Mapa',
    question: 'Gdzie może być problem?',
    price: '0 zł',
    copy: 'Krótka analiza obecnej sytuacji firmy i jej obecności online. Pokazuje, co zwraca uwagę, gdzie może znajdować się problem i co warto sprawdzić dokładniej.',
    chooseIf: 'Chcesz najpierw zobaczyć, gdzie może być problem.',
    audience: 'Dla firmy, która chce najpierw zorientować się w swojej sytuacji, zanim zdecyduje się na szerszą analizę.',
    includes: [
      'Najważniejsze obserwacje',
      'Prawdopodobny problem',
      'Istotna szansa',
      'Kierunek dalszej diagnozy',
    ],
    result: '0 zł. Bez zobowiązań.',
    cta: 'Sprawdź firmę bezpłatnie',
  },
  {
    id: 'start',
    code: '02',
    name: 'Mapa Start',
    question: 'Co powinienem zrobić najpierw?',
    price: '249 zł',
    copy: 'Dla firmy, która wie, że chce coś poprawić, ale nie chce podejmować kolejnej decyzji marketingowej na wyczucie.',
    chooseIf: 'Potrzebujesz zdecydować, co zrobić jako pierwsze.',
    audience: 'Dla właściciela firmy, który rozważa SEO, reklamy, zmianę strony, social media, zmianę oferty lub inne działania, ale nie wie jeszcze, które z nich powinny mieć pierwszeństwo.',
    includes: [
      'Diagnozę obecnej sytuacji',
      'Główny problem i jego znaczenie',
      '3 najważniejsze priorytety',
      'Pierwszy krok',
      'Listę „nie teraz”',
      'Plan działania na 30 dni',
      '45-minutowe omówienie wyników',
    ],
    result: 'Wiesz, co zrobić najpierw — i czego na razie nie robić.',
    cta: 'Wybieram Mapę Start',
  },
  {
    id: 'strategic',
    code: '03',
    name: 'Mapa Strategiczna',
    question: 'Co naprawdę ogranicza wynik?',
    price: '499 zł',
    copy: 'Szersza diagnoza dla firmy, która już inwestuje w marketing, korzysta z kilku kanałów lub stoi przed większą decyzją dotyczącą dalszych działań.',
    chooseIf: 'Już inwestujesz i chcesz ustalić, co naprawdę ogranicza wynik.',
    audience: 'Dla firm, które mają już działania, dane, wykonawców lub budżet, ale nie mają pewności, co rzeczywiście ogranicza wynik i gdzie skierować kolejny ruch.',
    includes: [
      'Diagnozę procesu pozyskiwania klientów',
      'Problem #1',
      'Priorytet i kolejność działań',
      'Rekomendacje wynikające z diagnozy',
      'Listę „nie teraz”',
      'Logikę pomiaru',
      'Kontekst konkurencji, jeśli pomaga podjąć decyzję',
      'Analizę dostępnych danych',
      '60-minutowe omówienie diagnozy',
    ],
    result: 'Wiesz, co naprawdę ogranicza wynik, co zrobić najpierw i czego jeszcze nie uruchamiać.',
    cta: 'Wybieram Mapę Strategiczną',
    featured: true,
  },
  {
    id: 'ai',
    code: '04',
    name: 'Mapa AI',
    question: 'Jak AI widzi Twoją firmę?',
    price: '149 zł',
    copy: 'Specjalistyczna analiza tego, jak systemy AI przedstawiają Twoją firmę, jej ofertę i pozycję na tle konkurencji.',
    chooseIf: 'Chcesz sprawdzić, jak Twoją firmę przedstawiają systemy AI.',
    audience: 'Dla firm, które chcą sprawdzić swoją obecność w odpowiedziach ChatGPT, Gemini, Claude i innych systemów AI.',
    includes: [
      'Widoczność marki',
      'Sposób przedstawiania firmy',
      'Źródła informacji',
      'Poprawność informacji',
      'Porównanie z konkurencją',
      'Najważniejsze luki',
      'Rekomendowane działania',
    ],
    result: 'Konkretna diagnoza tego, jak AI obecnie przedstawia Twoją firmę i co warto z tym zrobić.',
    cta: 'Wybieram Mapę AI',
  },
]

export const faqs = [
  {
    q: 'Czy DigitalMap jest dla firmy, która dopiero zaczyna?',
    a: 'Tak, jeśli istnieje już rynek, oferta lub pierwsze sygnały, które można ocenić. Przy bardzo wczesnym etapie możemy też powiedzieć wprost, że pełna diagnoza byłaby jeszcze przedwczesna i zacząć od Mini Mapy.',
  },
  {
    q: 'Mam już agencję, niezależnego specjalistę albo własny zespół marketingowy — czy Mapa ma sens?',
    a: 'Tak. DigitalMap może być niezależnym drugim spojrzeniem na obecne działania: co dziś jest priorytetem, czego może brakować, które założenia warto zweryfikować i jakie pytania warto zadać wykonawcy lub zespołowi.',
  },
  {
    q: 'Czy będziecie później próbowali sprzedać mi wdrożenie?',
    a: 'Wdrożenie jest opcją, nie warunkiem. Najpierw kończymy diagnozę. Jeśli wynik pokaże, że potrzebne jest konkretne wdrożenie, możemy przygotować zakres — ale rekomendację możesz zrealizować również poza DigitalMap.',
  },
  {
    q: 'Czy muszę później korzystać z DigitalMap?',
    a: 'Nie. Rekomendacje możesz wdrożyć samodzielnie, z własnym zespołem, obecną agencją, niezależnym specjalistą albo innym wykonawcą.',
  },
  {
    q: 'Czym Mapa różni się od klasycznego audytu?',
    a: 'Klasyczny audyt często kończy się listą rzeczy do poprawy. Mapa ma ustalić kolejność: co jest najważniejszym ograniczeniem, jakie dowody za tym stoją, co zrobić teraz, czego nie ruszać i co mierzyć.',
  },
  {
    q: 'Czy otrzymam gotową strategię?',
    a: 'Otrzymujesz diagnozę, priorytety, plan następnych ruchów i mierniki. To nie jest automatycznie pełna strategia wykonawcza dla każdego kanału — jej zakres wynika dopiero z tego, co diagnoza pokaże jako priorytet.',
  },
  {
    q: 'Jak długo trwa przygotowanie?',
    a: 'Termin zależy od wybranego zakresu i dostępnych danych. Potwierdzamy go przed startem, zamiast obiecywać sztucznego terminu gwarantowanego, którego nie da się konsekwentnie utrzymać.',
  },
  {
    q: 'Jakie dane muszę przekazać?',
    a: 'Na start wystarczy domena lub nazwa firmy i krótki kontekst. Jeśli masz GA4, Google Search Console, dane z kampanii, CRM lub inne źródła, możemy je wykorzystać tam, gdzie zwiększają pewność diagnozy.',
  },
  {
    q: 'Co jeśli nie mam GA4 albo Google Search Console?',
    a: 'To nie blokuje startu. Możemy zacząć od publicznie dostępnych danych, rynku, widoczności, komunikacji i ścieżki klienta. Poziom pewności wniosków pokazujemy wprost.',
  },
  {
    q: 'Czy analizujecie SEO, reklamy, social media i stronę?',
    a: 'Tak — jako elementy całej drogi klienta. Nie zakładamy jednak z góry, że któryś z tych kanałów jest problemem albo rozwiązaniem.',
  },
  {
    q: 'Czy konsultacja jest w cenie Mapy Strategicznej?',
    a: 'Tak. Mapa Strategiczna obejmuje 60-minutową konsultację, podczas której omawiamy diagnozę, rekomendacje, pytania i najbliższe decyzje.',
  },
  {
    q: 'W jakiej formie dostanę Mapę?',
    a: 'Dostajesz uporządkowaną Mapę diagnozy: problem, dowody, poziom pewności, priorytety, plan działania, rzeczy „nie teraz” i mierniki. Nie zostajesz z samą listą błędów.',
  },
  {
    q: 'Co jeśli chcę wdrożyć rekomendacje samodzielnie?',
    a: 'Możesz. Diagnoza nie wiąże Cię z DigitalMap ani z konkretnym wykonawcą.',
  },
]
